# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
community_bridge: PROJECT-NAME
GitHub Sponsors	github: USERNAME or github: [USERNAME, USERNAME, USERNAME, USERNAME]
IssueHunt	issuehunt: USERNAME
Ko-fi	ko_fi: USERNAME
Liberapay	liberapay: USERNAME
Open Collective	open_collective: USERNAME
Otechie	otechie: USERNAME
Patreon	patreon: USERNAME
Tidelift	tidelift: PLATFORM-NAME/PACKAGE-NAME
Custom URL	custom: LINK1 or custom: [LINK1, LINK2, LINK3, LINK4]
